### PR TITLE
Update By A Thread - Part 2.md

### PR DESCRIPTION
**Pull request by swiss-JF**
Alternative solution added, that would work, without the help of Paul.

### CODE REVIEW

**Review by swiss-JF — COMMENTED** [review]
Status: One way to find the solution will not be playable after CTF Ends

**Comment by hotpheex** [comment]
You left this one as a draft. Did you still want to change anything before I merge?
Looks good :)

**Comment by swiss-JF** [comment]
Hi, it was my first activity on github... not sure I did it correctly (well
your mail shows, that no...), but it was just to add alternate way. I
guess, it will make it to still playable after the CTF (if it’s the one
with the date of birth). So, feel free to amend and add. I will see if I
can change the status from draft later (just woke up).
Thanks again for the CTF, it was really good.

Am Montag, 8. Juni 2020 schrieb hotpheex <notifications@github.com>:

**Comment by hotpheex** [comment]
All good, thanks for the addition! :)

I'll merge the PR now.

**Pull request merged**
